### PR TITLE
GCC Options

### PR DESCRIPTION
**Pull request by ate-f**
Hi,

I've created a small change to allow GCC options to be passed.

### CODE REVIEW

**Comment by srod** [comment]
Hi,
I will take a look 👍 
Thank you !

**Comment by srod** [comment]
Merged with #190
Thanks !

**Comment by srod** [comment]
I've published 2.3.1 !

**Comment by ate-f** [comment]
Awesome, thanks for the quick turnaround! Regards, Ate

Op 24 sep. 2017 23:53 schreef "Rodolphe Stoclin" <notifications@github.com>:

**Pull request merged**
